RTOS_INC = \
FreeRTOS/Inc

RTOS_ARMCM3 = \
FreeRTOS/ARMCM3/Inc

RTOS_MIN = \
FreeRTOS/Common/Inc  \

RTOS_TEST_INC = \
FreeRTOS/parTest/Inc

RTOSINCLUDE = $(RTOS_MIN) $(RTOS_INC) $(RTOS_ARMCM3) $(RTOS_TEST_INC)